version: '3.8'

services:
  frontend:
    build: ../your-frontend-app
    ports:
      - "80:80"
    restart: always

  backend:
    build: .
    ports:
      - "5000:5000"
    environment:
      - DATABASE_URL=mysql://dbuser:dbpassword@db:3306/dbname
    depends_on:
      - db
    restart: always

  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: dbname
      MYSQL_USER: dbuser
      MYSQL_PASSWORD: dbpassword
    volumes:
      - db_data:/var/lib/mysql
    ports:
      - "3306:3306"
    restart: always

volumes:
  db_data:
